<?php

namespace Netflex\Toolbox\Providers;

use Illuminate\Foundation\Providers\ArtisanServiceProvider;
use Netflex\Toolbox\Commands\Orders\PruneOrders;

class CommandServiceProvider extends ArtisanServiceProvider
{

    protected $commands = [
        PruneOrders::class,
    ];


    public function register()
    {
        dd("lol");
        parent::register(); // TODO: Change the autogenerated stub
    }

}