<?php

class ToolboxProvider extends \Illuminate\Support\ServiceProvider
{

    public function register()
    {
        dd("lol");
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot() {

    }


}